template: istio-service
deployments:
  dev:
    target: dev
    clusters: 1
    values:
      image: <registryhost>/<owner>/<repository>
      tag: main
      port: 5000
      replicas: 1
      chartTag: 0.0.10
