template: istio-service
deployments:
  dev:
    target: dev
    clusters: 1
    values:
      image: ghcr.io/erikschlegel/coral-java-api-bigbang-test
      tag: main
      port: 5000
      replicas: 1
      chartTag: 0.0.10
