name: Java Container
on: [ push, pull_request ]

env:
  CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
  CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_ACCESS_TOKEN: ${{ secrets.CONTAINER_REGISTRY_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CONTAINER_IMAGE_NAME: ${{ github.repository }}
  CLOUD_NAME: AzureCloud
  IAC_SUFFIX: '${{ secrets.CLUSTER_NAME }}-${{ github.repository_owner }}'

jobs:
  check-secret:
    runs-on: ubuntu-latest

    outputs:
      my-key-exists: ${{ steps.my-key-check.outputs.defined }}

    steps:

      - name: Check for Secret availability
        id: my-key-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.AZURE_CREDENTIALS }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt

    - name: Build and Test
      run: ./mvnw --batch-mode --update-snapshots verify

    - name: "Install sbom-tool"
      run: |
        curl -Lo msft-sbom https://github.com/microsoft/sbom-tool/releases/download/v${MSFT_SBOM_VERSION}/sbom-tool-linux-x64
        chmod +x msft-sbom
        mv msft-sbom /usr/local/bin/msft-sbom
        rm -rf msft-sbom
      env:
        MSFT_SBOM_VERSION: 0.3.1

    - name: Generate sbom
      run: msft-sbom generate -b . -bc . -pn Test -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose

    - name: Upload sbom
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: ./_manifest/spdx_2.2/manifest.spdx.json

  push-gh:
    runs-on: ubuntu-latest
    needs: [ build , check-secret ]

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v2

      - name: Use Github Container Registry if no secrets are set
        run: echo "CONTAINER_REGISTRY_URL=ghcr.io" >> $GITHUB_ENV && echo "CONTAINER_REGISTRY_ACCESS_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV && echo "CONTAINER_REGISTRY_USER=\$GITHUB_USER" >> $GITHUB_ENV

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
      
      - name: "Install ORAS CLI"
        uses: oras-project/setup-oras@main
        with:
          version: 1.0.0

      - name: Login to Azure Cloud with CLI
        if: needs.check-secret.outputs.my-key-exists == 'true'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ env.CLOUD_NAME }}    

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ env.CONTAINER_REGISTRY_USER }}
          password: ${{ env.CONTAINER_REGISTRY_ACCESS_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.CONTAINER_REGISTRY_URL }}/${{ env.CONTAINER_IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Download sbom
        uses: actions/download-artifact@v3
        with:
          name: sbom

      - name: Attach sbom to image
        run: oras attach ${{ steps.meta.outputs.tags }} ./manifest.spdx.json:application/spdx+json --artifact-type org.example.sbom.v0      
      
      - name: downcase IAC_SUFFIX
        run: echo "IAC_SUFFIX=${IAC_SUFFIX,,}" >>${GITHUB_ENV}

      - name: downcase KEYVAULT_NAME
        if: needs.check-secret.outputs.my-key-exists == 'true'
        run: |
          KEYVAULT_NAME="vault-${IAC_SUFFIX}"
          KEYVAULT_SUBSTR=${KEYVAULT_NAME:0:23}
          echo "Val: $KEYVAULT_SUBSTR"
          echo "KEYVAULT_NAME=${KEYVAULT_SUBSTR,,}" >>${GITHUB_ENV}
          echo "KEYVAULT_URI=${KEYVAULT_SUBSTR}.vault.azure.net" >>${GITHUB_ENV} 

      - name: "Access key from Azure Key Vault and sign using cosign"
        if: needs.check-secret.outputs.my-key-exists == 'true'
        env:
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          # Get the Azure credentials and set them as environment variables
          export AZURE_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId | tr -d '"')
          export AZURE_CLIENT_ID=$(echo  $AZURE_CREDENTIALS | jq .clientId | tr -d '"')
          export AZURE_CLIENT_SECRET=$(echo  $AZURE_CREDENTIALS | jq -r .clientSecret | tr -d '"')
          export OBJECTID=$(az ad sp show --id $AZURE_CLIENT_ID --query 'id' -o tsv)
          az keyvault set-policy --name ${{ env.KEYVAULT_NAME }} --object-id $OBJECTID --key-permissions get sign --only-show-errors
          export COSIGN_PASSWORD=cosign-key
          cosign sign --key azurekms://${{ env.KEYVAULT_URI }}/cosign-key ${{ steps.meta.outputs.tags }} 
